### ISSUE TITLE
Error Message when trying to open in Jupyter Notebook

### ISSUE THREAD

**Issue by ChristopheBunn** [udacity/AIPND#7]
Hello, I downloaded **Mean Normalization and Data Separation.ipynb** from [https://github.com/udacity/AIPND/tree/master/NumPy%20Mini-Project](https://github.com/udacity/AIPND/tree/master/NumPy%20Mini-Project), but the following error message appeared when I tried to open the file in a Jupyter Notebook:

> "Unreadable Notebook: C:\Users\Christophe\Documents\Informatique\MOOC\Data Scientist Nanodegree - Udacity\Jupyter Notebooks\Mean Normalization and Data Separation.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")"

Any suggestions? Thanks.

**Comment by ScriptAutomate** [comment]
I'm not sure what you did wrong, as I am unable to reproduce your issue. It works for me. You must have downloaded it wrong.

If you look at the raw content, it is JSON, and it loads just fine locally:
https://raw.githubusercontent.com/udacity/AIPND/master/NumPy%20Mini-Project/Mean%20Normalization%20and%20Data%20Separation.ipynb

**Comment by sgalpha01** [comment]
> Hello, I downloaded **Mean Normalization and Data Separation.ipynb** from https://github.com/udacity/AIPND/tree/master/NumPy%20Mini-Project, but the following error message appeared when I tried to open the file in a Jupyter Notebook:
> 
> > "Unreadable Notebook: C:\Users\Christophe\Documents\Informatique\MOOC\Data Scientist Nanodegree - Udacity\Jupyter Notebooks\Mean Normalization and Data Separation.ipynb NotJSONError("Notebook does not appear to be JSON: '\n\n\n\n\n\n\n<html lang...")"
> 
> Any suggestions? Thanks.

I think you downloaded the file by right-clicking on the file and selecting "save link as...". Instead, you need to open the file and right-click on `Raw` button and do the same.

**Comment by abhiojha8** [comment]
"Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks"
